import { FormEvent, useEffect, useState } from 'react';
import { commerceService } from '../services/commerce.service';
import { ManualCustomer } from '../types/commerce';

const empty = { first_name:'', last_name:'', rut:'', phone:'', birth_date:'', observation:'', is_senior:true };

export function ManualCustomersPage() {
  const [items,setItems]=useState<ManualCustomer[]>([]), [query,setQuery]=useState(''), [filter,setFilter]=useState('all');
  const [form,setForm]=useState(empty), [selected,setSelected]=useState<ManualCustomer|null>(null), [message,setMessage]=useState(''), [showForm,setShowForm]=useState(false);
  async function load(){setItems(await commerceService.getManualCustomers(query,filter))}
  async function open(id:string){setSelected(await commerceService.getManualCustomer(id))}
  useEffect(()=>{const timer=setTimeout(()=>load().catch(e=>setMessage(e.message)),200);return()=>clearTimeout(timer)},[query,filter]);
  async function create(e:FormEvent){e.preventDefault();try{const result=await commerceService.createManualCustomer(form);setMessage(result.warning||'Cliente manual creado correctamente.');setForm(empty);setShowForm(false);await load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo crear')}}
  async function action(type:'STAMP'|'PURCHASE'|'POINTS'){if(!selected)return;const value=type==='POINTS'?Number(prompt('¿Cuántos puntos deseas sumar?','1')):1;if(!value)return;try{await commerceService.addManualMovement(selected.id,type,value);await open(selected.id);await load()}catch(e){setMessage(e instanceof Error?e.message:'No se pudo registrar')}}
  async function redeem(){if(!selected)return;try{await commerceService.redeemManualBenefit(selected.id);await open(selected.id)}catch(e){setMessage(e instanceof Error?e.message:'No se pudo canjear')}}
  async function toggle(){if(!selected)return;await commerceService.updateManualCustomer(selected.id,{status:selected.status==='ACTIVE'?'INACTIVE':'ACTIVE'});await open(selected.id);await load()}
  async function edit(){if(!selected)return;const first_name=prompt('Nombre',selected.firstName),last_name=prompt('Apellido',selected.lastName);if(!first_name||!last_name)return;await commerceService.updateManualCustomer(selected.id,{first_name,last_name,rut:prompt('RUT',selected.rut??'')??selected.rut,phone:prompt('Teléfono',selected.phone??'')??selected.phone,observation:prompt('Observación',selected.observation??'')??selected.observation});await open(selected.id);await load()}
  async function remove(){if(!selected||!confirm('¿Eliminar este cliente manual y su historial? Esta acción no afecta usuarios digitales.'))return;await commerceService.deleteManualCustomer(selected.id);setSelected(null);await load()}
  return <div className="page">
    <p className="eyebrow">Atención sin celular</p><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="title">Clientes manuales</h1><p className="subtitle">Adultos mayores y clientes que no usan la aplicación.</p></div><button className="primary" onClick={()=>setShowForm(v=>!v)}>Nuevo cliente manual</button></div>
    {message&&<p role="alert" className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">{message}</p>}
    {showForm&&<form onSubmit={create} className="mt-6 grid gap-4 rounded-3xl border bg-white p-6 md:grid-cols-2">
      <label>Nombre<input className="input" value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})} required/></label><label>Apellido<input className="input" value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})} required/></label>
      <label>RUT opcional<input className="input" value={form.rut} onChange={e=>setForm({...form,rut:e.target.value})}/></label><label>Teléfono opcional<input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label>
      <label>Fecha de nacimiento<input type="date" className="input" value={form.birth_date} onChange={e=>setForm({...form,birth_date:e.target.value})}/></label><label className="flex items-center gap-3"><input type="checkbox" checked={form.is_senior} onChange={e=>setForm({...form,is_senior:e.target.checked})}/> Adulto mayor / sin celular</label>
      <label className="md:col-span-2">Observación<textarea className="input" value={form.observation} onChange={e=>setForm({...form,observation:e.target.value})}/></label>{!form.rut&&!form.phone&&<p className="md:col-span-2 text-sm text-amber-700">Sin RUT ni teléfono será más difícil detectar duplicados.</p>}<button className="primary md:col-span-2">Guardar cliente</button>
    </form>}
    <div className="mt-6 flex flex-wrap gap-3"><input className="input max-w-md" placeholder="Buscar nombre, apellido, RUT o teléfono" value={query} onChange={e=>setQuery(e.target.value)}/><select className="input max-w-xs" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="senior">Solo adultos mayores</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></div>
    <div className="mt-4 overflow-hidden rounded-3xl border bg-white">{items.map(c=><button key={c.id} onClick={()=>open(c.id)} className="grid w-full grid-cols-[1fr_auto] border-t p-5 text-left first:border-0"><span><strong>{c.firstName} {c.lastName}</strong><small className="block text-slate-500">{c.rut||c.phone||'Sin identificador'} · {c.segment==='SENIOR'?'Adulto mayor':'General'}</small></span><span className={c.status==='ACTIVE'?'text-emerald-700':'text-slate-400'}>{c.status==='ACTIVE'?'Activo':'Inactivo'}</span></button>)}</div>
    {selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4" onClick={()=>setSelected(null)}><section className="mx-auto my-8 max-w-2xl rounded-3xl bg-white p-6" onClick={e=>e.stopPropagation()}>
      {selected.segment==='SENIOR'&&<p className="mb-4 rounded-2xl bg-amber-100 p-4 font-black text-amber-900">Cliente adulto mayor / atención manual</p>}<h2 className="text-2xl font-black">{selected.firstName} {selected.lastName}</h2><p className="text-slate-500">{selected.rut||'Sin RUT'} · {selected.phone||'Sin teléfono'}</p>
      <div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[['Sellos',selected.stamps],['Compras',selected.purchases],['Puntos',Number(selected.points)],['Beneficios',selected.availableBenefits]].map(([label,value])=><div key={label} className="rounded-2xl bg-slate-50 p-4"><small>{label}</small><strong className="block text-xl">{value}</strong></div>)}</div>{selected.program&&<p className="mt-4 text-sm">Programa: {Number(selected.programProgress)} de {selected.program.target} · {selected.program.reward}</p>}
      <div className="mt-5 grid grid-cols-2 gap-2 md:grid-cols-4"><button className="primary" onClick={()=>action('STAMP')}>Agregar sello</button><button className="primary" onClick={()=>action('PURCHASE')}>Agregar compra</button><button className="primary" onClick={()=>action('POINTS')}>Sumar puntos</button><button disabled={!selected.availableBenefits} className="primary disabled:opacity-40" onClick={redeem}>Canjear beneficio</button></div>
      <h3 className="mt-6 font-black">Historial</h3><ul className="mt-2 max-h-56 space-y-2 overflow-y-auto">{selected.movements?.map(m=><li key={m.id} className="rounded-xl bg-slate-50 p-3 text-sm">{m.type} · {Number(m.value)} · {new Date(m.createdAt).toLocaleString('es-CL')} {m.note&&`· ${m.note}`}</li>)}</ul>
      <button className="mt-5 w-full rounded-2xl border py-3 font-bold" onClick={edit}>Editar datos</button><button className="mt-2 w-full rounded-2xl border py-3 font-bold" onClick={toggle}>{selected.status==='ACTIVE'?'Desactivar cliente':'Activar cliente'}</button><button className="mt-2 w-full py-3 font-bold text-red-700" onClick={remove}>Eliminar cliente manual</button><button className="mt-2 w-full py-3 font-bold" onClick={()=>setSelected(null)}>Cerrar</button>
    </section></div>}
  </div>
}
