import { FormEvent,useState } from 'react';
import { CreateBusinessInput,Plan } from '../types/admin';

export function CreateBusinessForm({plans,onCancel,onSubmit}:{plans:Plan[];onCancel:()=>void;onSubmit:(input:CreateBusinessInput)=>Promise<void>}){
 const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const[field,setField]=useState<CreateBusinessInput>({name:'',businessType:'Cafetería',rutBusiness:'',address:'',phone:'',email:'',planId:plans[0]?.id??'',ownerName:'',ownerEmail:'',ownerPhone:'',ownerPassword:''});
 const change=(key:keyof CreateBusinessInput,value:string)=>setField(v=>({...v,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await onSubmit(field)}catch(e){setError(e instanceof Error?e.message:'No fue posible crear el comercio')}finally{setBusy(false)}}
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4"><form onSubmit={submit} className="mx-auto my-6 max-w-3xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="eyebrow">Alta comercial</p><h2 className="text-2xl font-black">Nuevo comercio y dueño</h2></div><button type="button" onClick={onCancel} className="secondary">Cerrar</button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="field">Nombre del comercio<input className="input" value={field.name} onChange={e=>change('name',e.target.value)} required/></label><label className="field">Rubro<input className="input" value={field.businessType} onChange={e=>change('businessType',e.target.value)} required/></label><label className="field">RUT empresa (opcional)<input className="input" value={field.rutBusiness} onChange={e=>change('rutBusiness',e.target.value)}/></label><label className="field">Plan<select className="input" value={field.planId} onChange={e=>change('planId',e.target.value)} required><option value="">Seleccionar plan</option>{plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field">Teléfono comercio<input className="input" value={field.phone} onChange={e=>change('phone',e.target.value)} required/></label><label className="field">Correo comercio<input className="input" type="email" value={field.email} onChange={e=>change('email',e.target.value)} required/></label><label className="field md:col-span-2">Dirección<input className="input" value={field.address} onChange={e=>change('address',e.target.value)} required/></label></div><h3 className="mt-7 text-lg font-black">Cuenta del dueño</h3><div className="mt-3 grid gap-4 md:grid-cols-2"><label className="field">Nombre<input className="input" value={field.ownerName} onChange={e=>change('ownerName',e.target.value)} required/></label><label className="field">Correo de acceso<input className="input" type="email" value={field.ownerEmail} onChange={e=>change('ownerEmail',e.target.value)} required/></label><label className="field">Teléfono<input className="input" value={field.ownerPhone} onChange={e=>change('ownerPhone',e.target.value)} required/></label><label className="field">Contraseña temporal<input className="input" type="password" minLength={8} value={field.ownerPassword} onChange={e=>change('ownerPassword',e.target.value)} required/></label></div>{error&&<p role="alert" className="mt-4 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}<button disabled={busy} className="primary mt-6 w-full">{busy?'Creando…':'Crear comercio y cuenta de dueño'}</button></form></div>
}
