import { apiRequest, AuthUser } from '@miclub/shared';
import { CustomerDashboard, CustomerProfile, CustomerRegistration } from '../types/customer';
const API_URL=import.meta.env.VITE_API_URL??'http://localhost:3000/api';
function profileFromUser(user:AuthUser):CustomerProfile{return{id:user.id,name:user.name,phone:user.phone,email:user.email||undefined,shortCode:`MC-${user.id.slice(-6).toUpperCase()}`}}
export const customerService={
 async getDashboard():Promise<CustomerDashboard>{const[home,rewards,history]=await Promise.all([apiRequest<any>('/customer/home'),apiRequest<any[]>('/customer/rewards'),apiRequest<any[]>('/customer/history')]);const p=home.primary_progress??{business:{name:'Sin programa activo'},current_value:0,target_value:1,next_reward:'Aún no tienes progreso'};return{progress:{business:p.business.name,current:Number(p.current_value),goal:Number(p.target_value),reward:p.next_reward},rewards:rewards.map(r=>({id:r.id,title:r.rewardDescription,business:r.business.name,status:r.status==='AVAILABLE'?'available':r.status==='REDEEMED'?'used':'expired',expiresAt:r.expiresAt?new Date(r.expiresAt).toLocaleDateString('es-CL'):undefined,usedAt:r.redeemedAt?new Date(r.redeemedAt).toLocaleDateString('es-CL'):undefined})),history:history.map(h=>({id:h.id,business:h.business.name,date:new Date(h.created_at).toLocaleString('es-CL'),action:h.status==='CANCELLED'?'Transacción anulada':'Compra registrada',progress:`+${h.value_added}`})),qrToken:home.qr.token,shortCode:home.qr.short_code}},
 getProfile(user:AuthUser):CustomerProfile{return profileFromUser(user)},
 async updateProfile(profile:CustomerProfile):Promise<CustomerProfile>{const updated=await apiRequest<any>('/users/me',{method:'PATCH',body:JSON.stringify({name:profile.name,phone:profile.phone,email:profile.email,birthDate:profile.birthDate,rut:profile.rut})});return{...profile,...updated,birthDate:updated.birthDate?.slice(0,10)}},
 async register(data:CustomerRegistration):Promise<void>{const response=await fetch(`${API_URL}/auth/register`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(Array.isArray(error.message)?error.message.join(', '):error.message??'No pudimos crear tu cuenta')}}
};
