import { FormEvent, useState } from 'react';
import { CustomerProfile } from '../types/customer';

const input='mt-1.5 w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 text-sm outline-none transition focus:border-violet-500 focus:ring-4 focus:ring-violet-100';
export function ProfileForm({profile,onSave}:{profile:CustomerProfile;onSave:(value:CustomerProfile)=>Promise<unknown>}){
  const[value,setValue]=useState(profile),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
  function change(field:keyof CustomerProfile,next:string){setValue(current=>({...current,[field]:next}));setSaved(false)}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);await onSave(value);setSaving(false);setSaved(true)}
  return <form onSubmit={submit} className="space-y-4"><label className="block text-sm font-semibold">Nombre<input className={input} value={value.name} onChange={e=>change('name',e.target.value)} required/></label><label className="block text-sm font-semibold">Teléfono<input className={input} type="tel" value={value.phone} onChange={e=>change('phone',e.target.value)} required/></label><label className="block text-sm font-semibold">Correo <span className="font-normal text-slate-400">(opcional)</span><input className={input} type="email" value={value.email??''} onChange={e=>change('email',e.target.value)}/><small className="mt-1 block font-normal text-slate-400">Opcional, puedes completarlo después</small></label><label className="block text-sm font-semibold">Fecha de nacimiento <span className="font-normal text-slate-400">(opcional)</span><input className={input} type="date" value={value.birthDate??''} onChange={e=>change('birthDate',e.target.value)}/><small className="mt-1 block font-normal text-slate-400">Opcional, puedes completarlo después</small></label><label className="block text-sm font-semibold">RUT <span className="font-normal text-slate-400">(opcional)</span><input className={input} value={value.rut??''} onChange={e=>change('rut',e.target.value)} placeholder="12.345.678-9"/><small className="mt-1 block font-normal text-slate-400">Opcional, puedes completarlo después</small></label><button disabled={saving} className="w-full rounded-2xl bg-slate-950 py-4 font-bold text-white disabled:opacity-50">{saving?'Guardando…':saved?'Cambios guardados ✓':'Guardar cambios'}</button></form>}
