import { ArrowRight,BarChart3,Check,Coffee,Dumbbell,Gift,HeartPulse,Leaf,MessageCircle,QrCode,RefreshCw,Scissors,ShoppingBasket,Smartphone,Store,TrendingUp,Users,Utensils } from 'lucide-react';
import { Link } from 'react-router-dom';
import { AccessForm,whatsappUrl } from '../components/AccessForm';
import { Brand } from '../components/Brand';

const problems=[[ShoppingBasket,'Tarjetas que se pierden','El papel se olvida, se rompe y no entrega información útil.'],[Users,'Sin datos de clientes','No sabes quién vuelve, quién dejó de comprar o quién está cerca de una recompensa.'],[BarChart3,'Promociones difíciles de medir','Descuentos sin seguimiento hacen difícil saber qué estrategia funciona.']] as const;
const steps=[['01','El cliente se registra con QR','Sin descargar aplicaciones ni completar formularios eternos.'],['02','El cajero registra la compra','Una operación rápida desde celular, tablet o computador.'],['03','El cliente acumula progreso','Ve en tiempo real cuánto le falta para su próxima recompensa.'],['04','El comercio entrega recompensas','Premias la preferencia y creas un motivo concreto para volver.']];
const benefits=[[TrendingUp,'Más clientes frecuentes','Convierte compras aisladas en relaciones que se repiten.'],[RefreshCw,'Más recompra','Dale a cada cliente una razón clara para regresar.'],[Gift,'Recompensas digitales','Sin tarjetas físicas, sellos ni procesos manuales.'],[BarChart3,'Dashboard simple','Revisa actividad, clientes y recompensas en un solo lugar.'],[QrCode,'QR de inscripción','Un acceso rápido y familiar para tus clientes.'],[Smartphone,'Paneles especializados','Experiencias claras para comercio, cajero y cliente.']] as const;
const industries=[[ShoppingBasket,'Minimarkets'],[Coffee,'Cafeterías'],[Scissors,'Barberías'],[Utensils,'Restaurantes'],[Leaf,'Verdulerías'],[HeartPulse,'Veterinarias'],[Dumbbell,'Gimnasios'],[Store,'Tiendas de barrio']] as const;
const plans=[{name:'MiClub Start',price:'$19.990',copy:'Ideal para comercios pequeños.',features:['1 programa activo','Hasta 500 clientes','3 colaboradores']},{name:'MiClub Business',price:'$39.990',copy:'Para comercios con más equipo o mayor flujo.',features:['Hasta 2.500 clientes','10 colaboradores','Reportes básicos'],featured:true},{name:'MiClub Enterprise',price:'Cotización',copy:'Para cadenas o necesidades especiales.',features:['Múltiples sucursales','Configuración personalizada','Soporte prioritario']}];

export function LandingPage(){return <div className="overflow-hidden bg-white">
 <header className="site-header"><div className="container-page flex h-24 items-center justify-between"><Brand/><nav className="hidden items-center gap-7 text-sm font-extrabold text-slate-600 lg:flex"><a href="#inicio">Inicio</a><a href="#como-funciona">Cómo funciona</a><a href="#beneficios">Beneficios</a><a href="#precios">Precios</a><a href="#acceso">Solicitar acceso</a></nav><a href="#acceso" className="header-cta">Solicitar acceso</a></div></header>
 <main>
  <section id="inicio" className="hero-section"><div className="hero-glow hero-glow-one"/><div className="hero-glow hero-glow-two"/><div className="container-page relative grid items-center gap-14 py-20 lg:grid-cols-[1.02fr_.98fr] lg:py-28"><div className="animate-rise"><span className="pill"><span/> Fidelización simple para comercios reales</span><h1 className="hero-title">Haz que tus clientes <em>quieran volver</em></h1><p className="hero-copy">MiClub Chile ayuda a comercios a fidelizar clientes, entregar recompensas y aumentar la recompra con una plataforma simple y rápida.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#acceso" className="button-primary">Solicitar acceso <ArrowRight size={19}/></a><a href={whatsappUrl} target="_blank" rel="noreferrer" className="button-secondary"><MessageCircle size={19}/> Cotizar por WhatsApp</a></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-sm font-bold text-slate-500"><span>✓ Sin tarjetas físicas</span><span>✓ Listo en minutos</span><span>✓ Soporte en Chile</span></div></div><ProductMockup/></div></section>
  <section className="section-pad bg-slate-950 text-white"><div className="container-page"><div className="section-heading"><p className="eyebrow text-cyan-300">El problema</p><h2>Tus clientes compran… pero ¿vuelven?</h2><p>Muchos comercios no saben quiénes son sus mejores clientes, cuándo dejaron de comprar o cómo motivarlos a regresar.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{problems.map(([Icon,title,text])=><article className="dark-card" key={title}><span className="icon-tile"><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section id="como-funciona" className="section-pad"><div className="container-page"><div className="section-heading"><p className="eyebrow">Una experiencia clara</p><h2>Con MiClub Chile, fidelizar es simple</h2><p>Un flujo fácil de entender para tu equipo y para tus clientes.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{steps.map(([n,title,text])=><article className="step-card" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section id="beneficios" className="section-pad soft-section"><div className="container-page"><div className="section-heading"><p className="eyebrow">Beneficios para tu negocio</p><h2>Todo lo necesario para convertir visitas en clientes frecuentes</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{benefits.map(([Icon,title,text])=><article className="benefit-card" key={title}><span><Icon/></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
  <section className="section-pad"><div className="container-page"><div className="section-heading text-center"><p className="eyebrow">Hecho para el comercio local</p><h2>MiClub se adapta a negocios como el tuyo</h2></div><div className="mx-auto mt-10 flex max-w-5xl flex-wrap justify-center gap-3">{industries.map(([Icon,name])=><span className="industry-pill" key={name}><Icon size={18}/>{name}</span>)}</div></div></section>
  <section className="founder-wrap"><div className="container-page"><div className="founder-card"><div><p className="eyebrow text-cyan-200">Cupos iniciales</p><h2>Programa Comercios Fundadores</h2><p>Estamos incorporando los primeros comercios que quieran probar MiClub Chile durante su etapa inicial.</p><a href="#acceso" className="button-light">Quiero ser comercio fundador <ArrowRight size={19}/></a></div><ul>{['Configuración inicial','QR para clientes','Panel comercio','Panel cajero','Soporte durante el piloto','Precio preferencial para fundadores'].map(x=><li key={x}><Check size={18}/>{x}</li>)}</ul></div></div></section>
  <section id="precios" className="section-pad"><div className="container-page"><div className="section-heading text-center"><p className="eyebrow">Planes simples</p><h2>Comienza según el tamaño de tu comercio</h2><p>También puedes comenzar con un piloto de 30 días.</p></div><div className="mx-auto mt-12 grid max-w-6xl gap-5 lg:grid-cols-3">{plans.map(p=><article className={`price-card ${p.featured?'price-featured':''}`} key={p.name}>{p.featured&&<b className="popular">Más elegido</b>}<h3>{p.name}</h3><p>{p.copy}</p><strong>{p.price}{p.price.startsWith('$')&&<small>/mes</small>}</strong><ul>{p.features.map(x=><li key={x}><Check size={18}/>{x}</li>)}</ul><a href="#acceso" className={p.featured?'button-primary':'button-secondary'}>Solicitar acceso</a></article>)}</div></div></section>
  <section id="acceso" className="section-pad access-section"><div className="container-page grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow">Hablemos de tu comercio</p><h2 className="text-4xl font-black tracking-tight md:text-5xl">Empieza a construir clientes que vuelven</h2><p className="mt-5 text-lg leading-relaxed text-slate-600">Cuéntanos sobre tu negocio. Te ayudamos a elegir un programa simple, atractivo y fácil de operar.</p><div className="mt-8 space-y-4">{['Respuesta directa y sin compromiso','Configuración acompañada','Piloto disponible por 30 días'].map(x=><p className="flex items-center gap-3 font-bold text-slate-700" key={x}><Check className="text-cyan-500"/>{x}</p>)}</div></div><AccessForm/></div></section>
 </main>
 <footer className="site-footer"><div className="container-page grid gap-8 py-12 md:grid-cols-[1fr_auto] md:items-center"><div><Brand/><p className="mt-4 font-semibold text-slate-400">Clientes que se unen, comercios que crecen.</p><a className="mt-2 block text-sm text-cyan-300" href="mailto:hola@miclubchile.cl">hola@miclubchile.cl</a></div><div className="flex flex-wrap gap-5 text-sm font-bold text-slate-300"><a href="https://app.miclubchile.cl">Panel cliente</a><a href="https://comercio.miclubchile.cl">Panel comercio</a><a href="https://cajero.miclubchile.cl">Panel cajero</a></div></div><div className="border-t border-white/10 py-5 text-center text-xs text-slate-500">© {new Date().getFullYear()} MiClub Chile. Todos los derechos reservados.</div></footer>
 </div>}

function ProductMockup(){return <div className="product-stage animate-rise"><div className="product-window"><div className="window-top"><span/><span/><span/><b>MiClub Comercio</b></div><div className="window-body"><aside><i/><i/><i/><i/></aside><div className="dashboard-mini"><div className="mini-head"><div><small>Resumen del comercio</small><h3>Hola, Café Central</h3></div><span><BarChart3/></span></div><div className="mini-stats"><article><small>Clientes activos</small><b>248</b><em>+18 este mes</em></article><article><small>Recompras</small><b>64%</b><em>+12% vs. mes anterior</em></article></div><div className="progress-preview"><div><small>Programa activo</small><strong>10 compras = 1 recompensa</strong></div><div className="progress-bars">{Array.from({length:10},(_,i)=><i className={i<7?'filled':''} key={i}/>)}</div></div></div></div></div><div className="floating-card floating-client"><span><Users/></span><div><small>Nuevo cliente</small><b>María se registró</b></div></div><div className="floating-card floating-reward"><span><Gift/></span><div><small>Recompensa</small><b>¡Beneficio desbloqueado!</b></div></div></div>}
