import { Injectable } from '@nestjs/common';import { JwtService } from '@nestjs/jwt';import { CycleStatus, RewardStatus } from '@prisma/client';import { PrismaService } from '../prisma/prisma.service';
@Injectable()
export class CustomerService {
  constructor(private readonly prisma:PrismaService,private readonly jwt:JwtService){}
  async home(userId:string){await this.expire(userId);const[customer,cycle,rewards,history]=await Promise.all([this.prisma.user.findUniqueOrThrow({where:{id:userId},select:{id:true,name:true,phone:true}}),this.prisma.cycle.findFirst({where:{customerUserId:userId,status:CycleStatus.ACTIVE},orderBy:{updatedAt:'desc'},include:{business:true,loyaltyProgram:true}}),this.prisma.reward.findMany({where:{customerUserId:userId,status:RewardStatus.AVAILABLE},orderBy:{generatedAt:'desc'},take:5,include:{business:true}}),this.history(userId,5)]);const qrToken=await this.jwt.signAsync({sub:userId,type:'customer_qr'},{expiresIn:'5m'});return{qr:{token:qrToken,short_code:`MC-${userId.slice(-6).toUpperCase()}`,expires_in_seconds:300},customer,primary_progress:cycle?{business:{id:cycle.business.id,name:cycle.business.name},cycle_id:cycle.id,current_value:Number(cycle.currentValue),target_value:Number(cycle.targetValue),next_reward:cycle.loyaltyProgram.rewardDescription}:null,rewards_available:rewards.map(r=>({id:r.id,business:r.business.name,description:r.rewardDescription,expires_at:r.expiresAt})),recent_history:history}}
  async rewards(userId:string){await this.expire(userId);return this.prisma.reward.findMany({where:{customerUserId:userId},orderBy:{generatedAt:'desc'},include:{business:{select:{id:true,name:true}}}})}
  async history(userId:string,take=50){const rows=await this.prisma.transaction.findMany({where:{customerUserId:userId},orderBy:{createdAt:'desc'},take,include:{business:{select:{id:true,name:true}}}});return rows.map(t=>({id:t.id,business:t.business,type:t.transactionType,value_added:Number(t.valueAdded),amount:t.amountOptional?Number(t.amountOptional):null,status:t.status,created_at:t.createdAt,cancelled_at:t.cancelledAt}))}
  private expire(userId:string){return this.prisma.reward.updateMany({where:{customerUserId:userId,status:RewardStatus.AVAILABLE,expiresAt:{lte:new Date()}},data:{status:RewardStatus.EXPIRED}})}
}
