import { Injectable,NotFoundException } from '@nestjs/common';import { BusinessStatus,Prisma,RewardStatus,TransactionStatus,UserStatus } from '@prisma/client';import { PrismaService } from '../prisma/prisma.service';import { PlanDto } from './dto/admin.dto';
@Injectable()export class AdminService{constructor(private readonly prisma:PrismaService){}
 async dashboard(){const start=new Date();start.setHours(0,0,0,0);const activeBusinesses=await this.prisma.business.findMany({where:{status:BusinessStatus.ACTIVE},include:{plan:true}});const[users,transactions,generated,redeemed,risk]=await Promise.all([this.prisma.user.count(),this.prisma.transaction.count({where:{status:TransactionStatus.VALID,createdAt:{gte:start}}}),this.prisma.reward.count({where:{generatedAt:{gte:start}}}),this.prisma.reward.count({where:{status:RewardStatus.REDEEMED,redeemedAt:{gte:start}}}),this.prisma.business.count({where:{status:{in:[BusinessStatus.SUSPENDED,BusinessStatus.GRACE_PERIOD]}}})]);return{activeBusinesses:activeBusinesses.length,registeredUsers:users,todayTransactions:transactions,rewardsGenerated:generated,rewardsRedeemed:redeemed,atRiskBusinesses:risk,estimatedMonthlyRevenue:activeBusinesses.reduce((s,b)=>s+Number(b.plan?.monthlyPrice??0),0)}}
 async businesses(){const rows=await this.prisma.business.findMany({include:{owner:{select:{name:true}},plan:true,_count:{select:{customers:true,transactions:true,rewards:true}}},orderBy:{createdAt:'desc'}});return Promise.all(rows.map(async b=>{const last=await this.prisma.transaction.findFirst({where:{businessId:b.id},orderBy:{createdAt:'desc'}});const days=last?(Date.now()-last.createdAt.getTime())/86400000:999;return{id:b.id,name:b.name,category:b.businessType,rut:b.rutBusiness,owner:b.owner.name,phone:b.phone,email:b.email,plan:b.plan?.name??'Sin plan',status:b.status.toLowerCase(),customers:b._count.customers,transactions:b._count.transactions,rewards:b._count.rewards,lastUse:last?.createdAt??null,usage:days<=3?'frequent':days<=14?'low':'inactive',activeProgram:(await this.prisma.loyaltyProgram.findFirst({where:{businessId:b.id,status:'ACTIVE'}}))?.name??'Sin programa'}}))}
 async business(id:string){const all=await this.businesses();return all.find(b=>b.id===id)??null}async businessStatus(id:string,status:string){const value=BusinessStatus[status.toUpperCase() as keyof typeof BusinessStatus];if(!value)throw new NotFoundException('Estado inválido');return this.prisma.business.update({where:{id},data:{status:value}})}
 async users(){return this.prisma.user.findMany({select:{id:true,name:true,phone:true,email:true,role:true,status:true,createdAt:true,businessMemberships:{select:{business:{select:{name:true}}}}},orderBy:{createdAt:'desc'}})}async user(id:string){return this.prisma.user.findUnique({where:{id},select:{id:true,name:true,phone:true,email:true,role:true,status:true,createdAt:true,businessMemberships:{select:{business:{select:{name:true}}}}}})}async userStatus(id:string,status:string){const value=UserStatus[status.toUpperCase() as keyof typeof UserStatus];if(!value)throw new NotFoundException('Estado inválido');return this.prisma.user.update({where:{id},data:{status:value}})}
 async plans(){const rows=await this.prisma.plan.findMany({orderBy:{monthlyPrice:'asc'}});return rows.map(p=>({...p,monthlyPrice:Number(p.monthlyPrice)}))}async createPlan(d:PlanDto){const p=await this.prisma.plan.create({data:{...d,monthlyPrice:new Prisma.Decimal(d.monthlyPrice),active:d.active??true}});return{...p,monthlyPrice:Number(p.monthlyPrice)}}async updatePlan(id:string,d:PlanDto){const p=await this.prisma.plan.update({where:{id},data:{...d,monthlyPrice:new Prisma.Decimal(d.monthlyPrice)}});return{...p,monthlyPrice:Number(p.monthlyPrice)}}
 async reports(){const month=new Date();month.setDate(1);month.setHours(0,0,0,0);const[newBusinesses,newUsers,monthlyTransactions,rewardsGenerated,rewardsRedeemed,activeBusinesses,suspendedBusinesses]=await Promise.all([this.prisma.business.count({where:{createdAt:{gte:month}}}),this.prisma.user.count({where:{createdAt:{gte:month}}}),this.prisma.transaction.count({where:{createdAt:{gte:month},status:TransactionStatus.VALID}}),this.prisma.reward.count({where:{generatedAt:{gte:month}}}),this.prisma.reward.count({where:{redeemedAt:{gte:month},status:RewardStatus.REDEEMED}}),this.prisma.business.count({where:{status:BusinessStatus.ACTIVE}}),this.prisma.business.count({where:{status:BusinessStatus.SUSPENDED}})]);return{newBusinesses,newUsers,monthlyTransactions,rewardsGenerated,rewardsRedeemed,activeBusinesses,suspendedBusinesses}}
}
