import { useEffect,useState } from 'react';
interface InstallPromptEvent extends Event{prompt():Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed';platform:string}>}
let deferredPrompt:InstallPromptEvent|null=null;const listeners=new Set<()=>void>();
if(typeof window!=='undefined'){window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event as InstallPromptEvent;listeners.forEach(fn=>fn())});window.addEventListener('appinstalled',()=>{deferredPrompt=null;listeners.forEach(fn=>fn())})}
const installed=()=>typeof window!=='undefined'&&(matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone));
export function PwaInstallPrompt({appName,message}:{appName:string;message?:string}){
 const key=`miclub:pwa-install:${appName.toLowerCase().replace(/\s+/g,'-')}`;const[visible,setVisible]=useState(false),[manual,setManual]=useState(false),[ready,setReady]=useState(Boolean(deferredPrompt));
 useEffect(()=>{const notify=()=>{setReady(Boolean(deferredPrompt));if(installed())setVisible(false)};listeners.add(notify);const params=new URLSearchParams(location.search);if(params.get('reset-pwa-install')==='1')localStorage.removeItem(key);const mobile=/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||matchMedia('(max-width: 820px)').matches;const postponed=Number(localStorage.getItem(key)||0),expired=Date.now()-postponed>3*86400000;if(!installed()&&mobile&&(!postponed||expired))setVisible(true);return()=>{listeners.delete(notify)}},[key]);
 async function install(){if(!deferredPrompt){setManual(true);return}await deferredPrompt.prompt();const choice=await deferredPrompt.userChoice;localStorage.setItem(`${key}:last-outcome`,choice.outcome);if(choice.outcome==='accepted')setVisible(false);else localStorage.setItem(key,String(Date.now()));deferredPrompt=null;setReady(false)}
 function later(){localStorage.setItem(key,String(Date.now()));setVisible(false)}
 if(!visible||installed())return null;const ios=/iPhone|iPad|iPod/i.test(navigator.userAgent);
 return <div role="dialog" aria-modal="true" aria-labelledby="pwa-install-title" className="fixed inset-0 z-[100] grid place-items-end bg-slate-950/50 p-3 sm:place-items-center"><section className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><p className="text-sm font-black uppercase tracking-wider text-violet-700">Acceso rápido</p><h2 id="pwa-install-title" className="mt-2 text-2xl font-black">Instala {appName}</h2><p className="mt-3 leading-relaxed text-slate-600">{message??`Instala ${appName} en tu celular para acceder más rápido.`}</p>{manual&&<div className="mt-4 rounded-2xl bg-violet-50 p-4 text-sm font-semibold text-violet-950">{ios?'Toca Compartir y luego “Agregar a pantalla de inicio”.':'Toca los 3 puntos del navegador y selecciona “Agregar a pantalla principal” o “Instalar aplicación”.'}</div>}<button onClick={install} className="mt-6 w-full rounded-2xl bg-violet-700 py-4 font-bold text-white">{ready?'Instalar ahora':'Ver cómo instalar'}</button><button onClick={later} className="mt-2 w-full py-3 font-bold text-slate-500">Más tarde</button></section></div>
}
