import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { AccumulationType, ManualCustomerSegment, ManualMovementType, ManualRegistrationReason, MembershipStatus, Prisma, ProgramStatus } from '@prisma/client';
import { BusinessAccessService } from '../businesses/business-access.service';
import { PrismaService } from '../prisma/prisma.service';
import { AddManualMovementDto, CreateManualCustomerDto, UpdateManualCustomerDto } from './dto/manual-customer.dto';

@Injectable()
export class ManualCustomersService {
  constructor(private readonly prisma:PrismaService,private readonly access:BusinessAccessService){}
  private rut(value?:string){return value?.replace(/[^0-9kK]/g,'').toUpperCase()||null}
  private phone(value?:string){const digits=value?.replace(/\D/g,'')??'';return digits?digits.length===8?`+569${digits}`:value!.startsWith('+')?`+${digits}`:digits:null}
  private async duplicate(businessId:string,rut:string|null,phone:string|null,excludeId?:string){if(!rut&&!phone)return null;return this.prisma.manualCustomer.findFirst({where:{businessId,id:excludeId?{not:excludeId}:undefined,OR:[...(rut?[{rut}]:[]),...(phone?[{phone}]:[])]},select:{id:true,firstName:true,lastName:true,rut:true,phone:true}})}
  async create(userId:string,dto:CreateManualCustomerDto){await this.access.requireMember(userId,dto.business_id);const rut=this.rut(dto.rut),phone=this.phone(dto.phone),duplicate=await this.duplicate(dto.business_id,rut,phone);if(duplicate)throw new ConflictException({message:'Ya existe un cliente manual con el mismo RUT o teléfono en este comercio.',duplicate});const customer=await this.prisma.manualCustomer.create({data:{businessId:dto.business_id,firstName:dto.first_name.trim(),lastName:dto.last_name.trim(),rut,phone,birthDate:dto.birth_date?new Date(dto.birth_date):null,segment:dto.is_senior?ManualCustomerSegment.SENIOR:ManualCustomerSegment.GENERAL,registrationReason:dto.registration_reason??ManualRegistrationReason.SENIOR,observation:dto.observation?.trim()||null,status:dto.status??MembershipStatus.ACTIVE}});return{...customer,warning:!rut&&!phone?'Este cliente no tiene RUT ni teléfono, puede ser más difícil evitar duplicados.':null}}
  async list(userId:string,businessId:string,q='',filter='all'){await this.access.requireMember(userId,businessId);const where:any={businessId};if(filter==='senior')where.segment=ManualCustomerSegment.SENIOR;if(filter==='active')where.status=MembershipStatus.ACTIVE;if(filter==='inactive')where.status=MembershipStatus.INACTIVE;if(q.trim()){const text=q.trim(),rut=this.rut(text),phone=this.phone(text);where.OR=[{firstName:{contains:text,mode:'insensitive'}},{lastName:{contains:text,mode:'insensitive'}},...(rut?[{rut:{contains:rut}}]:[]),...(phone?[{phone:{contains:phone}}]:[])]}return this.prisma.manualCustomer.findMany({where,orderBy:[{status:'asc'},{updatedAt:'desc'}],take:100})}
  async detail(userId:string,businessId:string,id:string){await this.access.requireMember(userId,businessId);const customer=await this.prisma.manualCustomer.findFirst({where:{id,businessId},include:{movements:{orderBy:{createdAt:'desc'},take:100,include:{performedBy:{select:{name:true}}}}}});if(!customer)throw new NotFoundException('Cliente manual no encontrado en este comercio');const program=await this.prisma.loyaltyProgram.findFirst({where:{businessId,status:ProgramStatus.ACTIVE},orderBy:{version:'desc'}});return{...customer,program:program?{type:program.accumulationType,target:Number(program.targetValue),reward:program.rewardDescription}:null}}
  async update(userId:string,businessId:string,id:string,dto:UpdateManualCustomerDto){await this.access.requireMember(userId,businessId);const current=await this.prisma.manualCustomer.findFirst({where:{id,businessId}});if(!current)throw new NotFoundException('Cliente manual no encontrado en este comercio');const rut=dto.rut===undefined?current.rut:this.rut(dto.rut),phone=dto.phone===undefined?current.phone:this.phone(dto.phone);const duplicate=await this.duplicate(businessId,rut,phone,id);if(duplicate)throw new ConflictException('Ya existe otro cliente manual con el mismo RUT o teléfono en este comercio.');return this.prisma.manualCustomer.update({where:{id},data:{firstName:dto.first_name?.trim(),lastName:dto.last_name?.trim(),rut,phone,birthDate:dto.birth_date?new Date(dto.birth_date):dto.birth_date===''?null:undefined,segment:dto.is_senior===undefined?undefined:dto.is_senior?ManualCustomerSegment.SENIOR:ManualCustomerSegment.GENERAL,registrationReason:dto.registration_reason,observation:dto.observation?.trim(),status:dto.status}})}
  async addMovement(userId:string,id:string,dto:AddManualMovementDto){await this.access.requireMember(userId,dto.business_id);return this.prisma.$transaction(async tx=>{const customer=await tx.manualCustomer.findFirst({where:{id,businessId:dto.business_id}});if(!customer)throw new NotFoundException('Cliente manual no encontrado en este comercio');if(customer.status!==MembershipStatus.ACTIVE)throw new BadRequestException('El cliente manual está inactivo');const program=await tx.loyaltyProgram.findFirst({where:{businessId:dto.business_id,status:ProgramStatus.ACTIVE},orderBy:{version:'desc'}});if(!program)throw new BadRequestException('El comercio no tiene un programa activo');const value=dto.type===ManualMovementType.STAMP||dto.type===ManualMovementType.PURCHASE?1:(dto.value??0);if(value<=0)throw new BadRequestException('El valor debe ser mayor que cero');const expected=program.accumulationType===AccumulationType.POINTS?ManualMovementType.POINTS:program.accumulationType===AccumulationType.VISIT_COUNT?ManualMovementType.STAMP:ManualMovementType.PURCHASE;const matchesProgram=dto.type===expected,progress=Number(customer.programProgress)+(matchesProgram?value:0),target=Number(program.targetValue),earned=matchesProgram?Math.floor(progress/target):0,remainder=matchesProgram?progress%target:Number(customer.programProgress);const data:any={programProgress:new Prisma.Decimal(remainder),availableBenefits:{increment:earned}};if(dto.type===ManualMovementType.POINTS)data.points={increment:new Prisma.Decimal(value)};if(dto.type===ManualMovementType.STAMP)data.stamps={increment:1};if(dto.type===ManualMovementType.PURCHASE)data.purchases={increment:1};await tx.manualCustomerMovement.create({data:{manualCustomerId:id,businessId:dto.business_id,performedByUserId:userId,type:dto.type,value:new Prisma.Decimal(value),note:dto.note}});const updated=await tx.manualCustomer.update({where:{id},data});return{customer:updated,benefits_earned:earned,reward:earned?program.rewardDescription:null,advanced_program:matchesProgram}})}
  async redeem(userId:string,businessId:string,id:string,note?:string){await this.access.requireMember(userId,businessId);return this.prisma.$transaction(async tx=>{const customer=await tx.manualCustomer.findFirst({where:{id,businessId}});if(!customer)throw new NotFoundException('Cliente manual no encontrado en este comercio');if(customer.availableBenefits<1)throw new ConflictException('El cliente no tiene beneficios disponibles');const program=await tx.loyaltyProgram.findFirst({where:{businessId,status:ProgramStatus.ACTIVE},orderBy:{version:'desc'}});await tx.manualCustomerMovement.create({data:{manualCustomerId:id,businessId,performedByUserId:userId,type:ManualMovementType.BENEFIT_REDEEMED,value:1,note:note||program?.rewardDescription}});return tx.manualCustomer.update({where:{id},data:{availableBenefits:{decrement:1},redeemedBenefits:{increment:1}}})})}
  async remove(userId:string,businessId:string,id:string){await this.access.requireMember(userId,businessId);const customer=await this.prisma.manualCustomer.findFirst({where:{id,businessId}});if(!customer)throw new NotFoundException('Cliente manual no encontrado en este comercio');await this.prisma.manualCustomer.delete({where:{id}});return{deleted:true}}
}
