import assert from 'node:assert/strict';import { ConflictException,ForbiddenException,NotFoundException } from '@nestjs/common';import { ManualMovementType,MembershipStatus } from '@prisma/client';import { ManualCustomersService } from '../backend/api/src/manual-customers/manual-customers.service';
const rows:any[]=[],moves:any[]=[],digitalUsers=[{id:'digital-1'}];let seq=0;const allowed:Record<string,string[]|undefined>={admin:['a'],cashier:['a'],managerB:['b'],intruder:[]};
const access={requireMember:async(userId:string,businessId:string)=>{if(!allowed[userId]?.includes(businessId))throw new ForbiddenException()}};
function matches(row:any,where:any){if(where.id&&typeof where.id==='string'&&row.id!==where.id)return false;if(where.id?.not&&row.id===where.id.not)return false;if(where.businessId&&row.businessId!==where.businessId)return false;if(where.status&&row.status!==where.status)return false;if(where.segment&&row.segment!==where.segment)return false;if(where.OR){const ok=where.OR.some((part:any)=>{const [field,condition]=Object.entries(part)[0] as any;if(typeof condition==='string')return row[field]===condition;if(condition?.contains)return String(row[field]??'').toLowerCase().includes(String(condition.contains).toLowerCase());return false});if(!ok)return false}return true}
const manualCustomer={findFirst:async({where}:any)=>rows.find(r=>matches(r,where))??null,create:async({data}:any)=>{const row={id:`m${++seq}`,status:'ACTIVE',segment:'GENERAL',points:0,stamps:0,purchases:0,programProgress:0,availableBenefits:0,redeemedBenefits:0,createdAt:new Date(),updatedAt:new Date(),...data};rows.push(row);return row},findMany:async({where}:any)=>rows.filter(r=>matches(r,where)),update:async({where,data}:any)=>{const row=rows.find(r=>r.id===where.id);for(const[k,v]of Object.entries(data)){if(v&&typeof v==='object'&&'increment'in(v as any))row[k]=Number(row[k])+Number((v as any).increment);else if(v&&typeof v==='object'&&'decrement'in(v as any))row[k]=Number(row[k])-Number((v as any).decrement);else if(v!==undefined)row[k]=v}return row},delete:async({where}:any)=>{const i=rows.findIndex(r=>r.id===where.id);return rows.splice(i,1)[0]}};
const prisma:any={manualCustomer,manualCustomerMovement:{create:async({data}:any)=>{const move={id:`x${moves.length+1}`,createdAt:new Date(),...data};moves.push(move);return move}},loyaltyProgram:{findFirst:async({where}:any)=>({id:`p-${where.businessId}`,businessId:where.businessId,status:'ACTIVE',accumulationType:'POINTS',targetValue:10,rewardDescription:'Beneficio prueba'})},$transaction:(fn:any)=>fn(prisma)};
const service=new ManualCustomersService(prisma,access as any);
async function run(){
 const a=await service.create('admin',{business_id:'a',first_name:'Elena',last_name:'Rojas',rut:'12.345.678-5',phone:'98765432',is_senior:true});assert.equal(a.segment,'SENIOR');assert.equal(digitalUsers.length,1); // 1
 assert.equal((await service.list('cashier','a','Elena','all')).length,1);assert.equal((await service.list('cashier','a','123456785','all')).length,1);assert.equal((await service.list('cashier','a','+56998765432','all')).length,1); // 2
 await service.addMovement('cashier',a.id,{business_id:'a',type:ManualMovementType.STAMP,value:1});await service.addMovement('cashier',a.id,{business_id:'a',type:ManualMovementType.PURCHASE,value:1});await service.addMovement('cashier',a.id,{business_id:'a',type:ManualMovementType.POINTS,value:10});assert.equal(rows[0].stamps,1);assert.equal(rows[0].purchases,1);assert.equal(rows[0].points,10);assert.equal(rows[0].availableBenefits,1); // 3
 await service.redeem('cashier','a',a.id);assert.equal(rows[0].availableBenefits,0);assert.equal(rows[0].redeemedBenefits,1);assert.equal(moves.at(-1).type,'BENEFIT_REDEEMED'); // 4
 await assert.rejects(()=>service.create('admin',{business_id:'a',first_name:'Duplicada',last_name:'Rojas',rut:'12.345.678-5'}),ConflictException); // 5
 const b=await service.create('managerB',{business_id:'b',first_name:'Elena',last_name:'Rojas',rut:'12.345.678-5',is_senior:true});assert.notEqual(a.id,b.id);assert.equal(b.points,0); // 6
 await assert.rejects(()=>service.detail('intruder','a',a.id),ForbiddenException);await assert.rejects(()=>service.detail('admin','a',b.id),NotFoundException); // 7
 assert.equal(digitalUsers.length,1); // 8/9: no tabla User fue mutada
 await service.update('admin','a',a.id,{status:MembershipStatus.INACTIVE,observation:'Atención preferente'});assert.equal(rows.find(r=>r.id===b.id).status,'ACTIVE');assert.equal(digitalUsers.length,1); // 9
 const anonymous=await service.create('admin',{business_id:'a',first_name:'Sin',last_name:'Identificador'});assert.match(anonymous.warning,/más difícil evitar duplicados/);await service.remove('admin','a',anonymous.id);assert.equal(digitalUsers.length,1); // 10 y eliminación aislada
 console.log('OK: 10 casos de clientes manuales verificados');
}
run().catch(e=>{console.error(e);process.exitCode=1});
