import { useEffect,useState } from 'react';import { AuthUser,logout,portalByRole,restoreSession } from '@miclub/shared';import { HashRouter,Navigate,Outlet,Route,Routes,useNavigate } from 'react-router-dom';
import { CommerceLayout } from './layouts/CommerceLayout';import { CollaboratorsPage } from './pages/CollaboratorsPage';import { CustomersPage } from './pages/CustomersPage';import { DashboardPage } from './pages/DashboardPage';import { LoginPage } from './pages/LoginPage';import { ProgramPage } from './pages/ProgramPage';import { QRMaterialPage } from './pages/QRMaterialPage';import { RewardsPage } from './pages/RewardsPage';import { SettingsPage } from './pages/SettingsPage';import { commerceService } from './services/commerce.service';import { BusinessSettings,DashboardSummary,LoyaltyProgram,QRMaterial } from './types/commerce';
function Protected({user}:{user:AuthUser|null}){if(!user)return <Navigate to="/login" replace/>;if(!['BUSINESS_OWNER','BUSINESS_ADMIN'].includes(user.role))return <main className="grid min-h-screen place-items-center"><div><h1>Sin permiso</h1><a href={portalByRole[user.role]}>Ir al portal autorizado</a></div></main>;return <Outlet/>}
function AppRoutes(){
 const[user,setUser]=useState<AuthUser|null>(null);const[ready,setReady]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[settings,setSettings]=useState<BusinessSettings|null>(null);const[program,setProgram]=useState<LoyaltyProgram|null>(null);const[dashboard,setDashboard]=useState<DashboardSummary|null>(null);const[qr,setQr]=useState<QRMaterial|null>(null);const navigate=useNavigate();
 useEffect(()=>{restoreSession().then(async session=>{if(!['BUSINESS_OWNER','BUSINESS_ADMIN'].includes(session.role)){await logout();setUser(null);return}setUser(session)}).catch(()=>setUser(null)).finally(()=>setReady(true))},[]);
 useEffect(()=>{if(!user)return;setLoading(true);Promise.all([commerceService.getBusinessSettings(),commerceService.getLoyaltyProgram(),commerceService.getBusinessDashboard(),commerceService.getQRMaterial()]).then(([s,p,d,q])=>{setSettings(s);setProgram(p);setDashboard(d);setQr(q as QRMaterial)}).catch(e=>setError(e instanceof Error?e.message:'Error de conexión')).finally(()=>setLoading(false))},[user]);
 async function out(){await logout();commerceService.reset();setUser(null);navigate('/login',{replace:true})}
 if(!ready)return <main className="grid min-h-screen place-items-center bg-emerald-950 text-white">Preparando tu comercio…</main>;
 if(!user)return <Routes><Route path="*" element={<LoginPage onLogin={setUser}/>}/></Routes>;
 if(loading||!settings)return <main className="grid min-h-screen place-items-center">{error||'Cargando comercio…'}</main>;
 return <Routes><Route element={<Protected user={user}/>}> <Route element={<CommerceLayout businessName={settings.name} onLogout={out}/>}> <Route path="/dashboard" element={dashboard?<DashboardPage summary={dashboard} program={program}/>:null}/><Route path="/program" element={<ProgramPage initial={program} onChange={setProgram}/>}/><Route path="/customers" element={<CustomersPage/>}/><Route path="/collaborators" element={<CollaboratorsPage/>}/><Route path="/rewards" element={<RewardsPage/>}/><Route path="/qr-material" element={qr?<QRMaterialPage material={qr}/>:null}/><Route path="/settings" element={<SettingsPage settings={settings} onChange={setSettings} onLogout={out}/>}/></Route></Route><Route path="*" element={<Navigate to="/dashboard" replace/>}/></Routes>;
}
export function App(){return <HashRouter><AppRoutes/></HashRouter>}
